# Generated by Django 4.2.4 on 2023-08-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('composition', models.TextField(verbose_name='Состав')),
                ('size', models.TextField(verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Букет',
                'verbose_name_plural': 'Букеты',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=10, verbose_name='Телефон')),
                ('datetime_created', models.DateTimeField(verbose_name='Дата создания заказа')),
            ],
            options={
                'verbose_name': 'Консультация',
                'verbose_name_plural': 'Консультации',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=10, verbose_name='Телефон')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес доставки')),
                ('datetime_created', models.DateTimeField(verbose_name='Дата создания заказа')),
                ('bouquet', models.ManyToManyField(related_name='orders', to='shop.bouquet')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='bouquet',
            name='events',
            field=models.ManyToManyField(related_name='bouquets', to='shop.event', verbose_name='Подходящие события'),
        ),
    ]
