# Generated by Django 4.2.4 on 2023-08-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-datetime_created'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='bouquet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='order',
            name='deliver',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Создан'), ('ASSEMBLE', 'Собирается'), ('READY', 'Готов к выдаче'), ('DONE', 'Доставлен')], default='NEW', max_length=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-datetime_created', 'address'], name='shop_order_datetim_e6d771_idx'),
        ),
    ]
