# Generated by Django 4.2.4 on 2023-08-25 17:13

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_options_bouquet_photo_order_deliver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон'),
        ),
    ]
